#pragma kernel CSMain

struct MeshInfo {
	float3 position;
	float3 normal;
};

RWTexture2D<float4> OutPosition;
RWTexture2D<float4> OutNormal;
StructuredBuffer<MeshInfo> Info;
int VertCount;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	int index = id.y * VertCount + id.x;
	MeshInfo info = Info[index];

	OutPosition[id.xy] = float4(info.position, 1.0);
	OutNormal[id.xy] = float4(info.normal, 1.0);
}